# About the Author {-}

My professional bio reads "Martin Monkman has three decades of expertise supporting evidence-based policy and business management decisions by gathering data from existing sources and through original collection (including surveys), then using data science and statistical methods to generate understanding, and communicating that information through reports and visualization."

What does this really mean? I have spent a long time finding data—often very messy data—and then using different analytic techniques to provide insights through statistical and data science methods, which in turn help organizations make better decisions. I spent many years working as part of BC Stats, the provincial statistics bureau in British Columbia, Canada, including a decade with the job title, "Provincial Statistician". In that context, the questions were often associated with public policy and the operations of public agencies (including human resources research). I now do similar work for public and private sector clients as part of the Consulting Services team at MNP, one of Canada's leading professional service firms. These experiences, including some of the in-real-life data that I have encountered along the way, have influenced what is in this book.

I also teach courses in the Business Intelligence and Data Analytics program at the University of Victoria's Continuing Studies department. This experience has also informed the content of this book—some of the lessons in those courses have found their way into this book. 

I hold Bachelor of Science and Master of Arts degrees in Geography from the University of Victoria. I am a Carpentries Instructor, and also a member of the Statistical Society of Canada (SSC) and the Society for American Baseball Research (SABR).



<!-- 
This file by Martin Monkman is licensed under a Creative Commons Attribution 4.0 International License. 
-->

