---
output:
  pdf_document: default
  html_document: default
---


<!-- 
This file by Martin Monkman is licensed under a Creative Commons Attribution 4.0 International License. 
-->



```{r setup_ch500, include=FALSE}

# packages

```


# Clean data principles {#clean-data}

placeholder for chapter 5


* The principles of data quality

* Understanding what makes data “dirty”, and why context matters

* Understanding tidy data principles

* Serving the research question



[@De_Jonge_van_der_Loo_2013]

[@Hubbard_data_cleaning_2017]


## Data Quality

[@Ligon_1996]

[@Ligon_2015], [@Ligon_2007]




## Structure

The first place to start with cleaning your data is the structure.


### Tidy data

Tidy data\index{tidy data}

[@tidydata]



### Row counts (records)

Did your import step give you as many rows as you anticipated?


### Columns (variables)

Did your import step capture all of the variables?

Did the variables import as the correct classes?

Things to look for:

* did variables that should be numbers load as numeric types, or as character?

* if working with labelled variables, did they load as factor type?



## Validation {#validation-intro}



## Feature engineering

[@R-bcEpiRate]

